const grid=document.querySelector('#grid'),search=document.querySelector('#search'),techFilter=document.querySelector('#techFilter'),soundOnly=document.querySelector('#soundOnly'),resultCount=document.querySelector('#resultCount'),empty=document.querySelector('#empty'),categoryFilters=document.querySelector('#categoryFilters');
let sites=[],category='All',lang=localStorage.getItem('motion-atlas-lang')||'en';
const categories=['All','3D World','Particles','Mouse','Scroll','Game','Generative','Sound','Experimental'];
const categoryCN={All:'全部','3D World':'3D 世界',Particles:'粒子',Mouse:'鼠标互动',Scroll:'滚动叙事',Game:'游戏体验',Generative:'生成艺术',Sound:'声音互动',Experimental:'实验设计'};
const copy={
  en:{navArchive:'THE INTERACTIVE WEB<br><span>ARCHIVE / 2026</span>',heroKicker:'CURATED DIGITAL EXPERIENCES',heroTitle:'Explore the<br><em>living web.</em>',heroDek:"A curated collection of the world's most remarkable 3D, WebGL, generative and interactive websites.",heroExperiences:'EXPERIENCES',heroCategories:'08 CATEGORIES',updated:'UPDATED WEEKLY',scroll:'SCROLL TO DISCOVER',index:'INDEX / 001—050',archiveTitle:'Curated<br>experiences.',archiveDek:'From spatial storytelling to particle experiments, sound interaction and AI-generated worlds. Every entry includes a concise experience guide and technology index.',tech:'TECH',soundOnly:'With sound',random:'Surprise me',hover:'HOVER TO REVEAL',empty:'No experiences match these filters.',clear:'Clear filters',point:'OUR POINT OF VIEW',quote:'“The web should feel less like a document<br>and more like <em>a place.</em>”',verbs:'<span>DISCOVER</span><span>STUDY</span><span>CREATE</span><span>SHARE</span>',footerLine:'A living index of remarkable interactions.',openSource:'OPEN SOURCE · 2026',placeholder:'Search names, effects or technology…',allTech:'All technologies',count:'EXPERIENCES',switch:'中文'},
  zh:{navArchive:'全球互动网页<br><span>图鉴 / 2026</span>',heroKicker:'精选数字互动体验',heroTitle:'探索这个<br><em>会呼吸的网络。</em>',heroDek:'全球最值得体验的 3D、WebGL、生成艺术与互动网页。按照视觉风格、技术方案和交互方式探索。',heroExperiences:'个体验',heroCategories:'08 个分类',updated:'每周更新',scroll:'向下探索',index:'图鉴 / 001—050',archiveTitle:'精选互动<br>体验图鉴。',archiveDek:'从空间叙事到粒子实验，从声音交互到 AI 生成。每一个案例都提供清晰的体验说明和技术索引。',tech:'技术',soundOnly:'包含声音',random:'随机探索',hover:'悬停揭晓',empty:'没有找到符合条件的体验。',clear:'清除筛选',point:'我们的观点',quote:'“网络不应只像一份文档，<br>它更应该成为<em>一个地方。</em>”',verbs:'<span>发现</span><span>研究</span><span>创造</span><span>分享</span>',footerLine:'持续生长的非凡互动图鉴。',openSource:'开放源代码 · 2026',placeholder:'搜索名称、效果或技术…',allTech:'全部技术',count:'个体验',switch:'EN'}
};
const palettes=[['#ff826c','#ffcf7a','#742e5e'],['#7de8d2','#b8ff6a','#285a6c'],['#8c7cff','#e8a7ff','#473477'],['#63b8ff','#9cf1ff','#214268'],['#ffcf5c','#ff7777','#6d2f38'],['#7ad97d','#e8ff8b','#24583d'],['#ef9ce8','#ffcfdf','#693d71'],['#ff945e','#e9d56b','#74351e']];

function buildCategories(){categoryFilters.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.textContent=lang==='zh'?categoryCN[c]:(c==='All'?'All':c);b.className=c===category?'active':'';b.onclick=()=>{category=c;buildCategories();render()};categoryFilters.appendChild(b)})}
function setupTech(){techFilter.length=1;[...new Set(sites.flatMap(x=>x.technologies))].sort().forEach(t=>techFilter.add(new Option(t,t)))}
function visual(type){const key=type.toLowerCase().replace(/\s+/g,'-');return `<div class="visual v-${key}"><i></i><i></i><i></i><i></i><b></b></div>`}
function card(s,index){const [a,b,c]=palettes[index%palettes.length],cat=lang==='zh'?categoryCN[s.category]:s.category;return `<a class="card" href="${s.url}" target="_blank" rel="noreferrer" style="--a:${a};--b:${b};--c:${c};--delay:${(index%7)*-.4}s"><div class="cover">${visual(s.category)}<div class="door left-door"></div><div class="door right-door"></div><span class="cover-question">?</span><span class="cover-num">${s.id} / ${cat.toUpperCase()}</span><span class="cover-arrow">↗</span><div class="reveal-title"><small>${cat}</small><strong>${s.name}</strong></div></div><div class="card-body"><div class="card-title"><h3>${s.name}</h3><span>${new URL(s.url).hostname.replace('www.','')}</span></div><p>${lang==='zh'?s.description.zh:s.description.en}</p><div class="tags">${s.technologies.slice(0,3).map(x=>`<span>${x}</span>`).join('')}${s.interactions.slice(0,2).map(x=>`<span class="interaction">${x}</span>`).join('')}</div></div></a>`}
function filtered(){const q=search.value.trim().toLowerCase();return sites.filter(s=>(category==='All'||s.category===category)&&(techFilter.value==='all'||s.technologies.includes(techFilter.value))&&(!soundOnly.checked||s.hasSound)&&(!q||[s.name,s.description.en,s.description.zh,s.category,...s.technologies,...s.interactions].join(' ').toLowerCase().includes(q)))}
function render(){const list=filtered();grid.innerHTML=list.map(s=>card(s,sites.indexOf(s))).join('');resultCount.textContent=lang==='zh'?`${String(list.length).padStart(2,'0')} ${copy.zh.count}`:`${String(list.length).padStart(2,'0')} ${copy.en.count}`;empty.classList.toggle('show',!list.length);if(matchMedia('(pointer:coarse)').matches)grid.querySelectorAll('.card').forEach(card=>card.addEventListener('click',e=>{if(!card.classList.contains('revealed')){e.preventDefault();grid.querySelectorAll('.revealed').forEach(x=>x.classList.remove('revealed'));card.classList.add('revealed')}}))}
function applyLanguage(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=copy[lang][el.dataset.i18n]);search.placeholder=copy[lang].placeholder;techFilter.options[0].text=copy[lang].allTech;document.querySelector('#langBtn').textContent=copy[lang].switch;buildCategories();render()}
document.querySelector('#langBtn').onclick=()=>{lang=lang==='en'?'zh':'en';localStorage.setItem('motion-atlas-lang',lang);applyLanguage()};
[search,techFilter,soundOnly].forEach(el=>el.addEventListener(el===search?'input':'change',render));document.querySelector('#clearBtn').onclick=()=>{search.value='';techFilter.value='all';soundOnly.checked=false;category='All';buildCategories();render()};document.querySelector('#randomBtn').onclick=()=>{const list=filtered();if(list.length)window.open(list[Math.floor(Math.random()*list.length)].url,'_blank','noopener')};

const canvas=document.querySelector('#ambient'),ctx=canvas.getContext('2d');let particles=[],mouse={x:.7,y:.3};function resize(){canvas.width=innerWidth*Math.min(devicePixelRatio,2);canvas.height=innerHeight*Math.min(devicePixelRatio,2);particles=Array.from({length:Math.min(180,Math.floor(innerWidth/7))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,z:Math.random(),v:.1+Math.random()*.4}))}addEventListener('resize',resize);addEventListener('pointermove',e=>mouse={x:e.clientX/innerWidth,y:e.clientY/innerHeight});resize();function draw(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#080909';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(w*mouse.x,h*mouse.y,0,w*mouse.x,h*mouse.y,w*.65);g.addColorStop(0,'rgba(113,142,28,.12)');g.addColorStop(.4,'rgba(24,34,20,.06)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(const p of particles){p.y-=p.v;p.x+=Math.sin(p.y*.003)*.08;if(p.y<0){p.y=h;p.x=Math.random()*w}ctx.fillStyle=`rgba(205,255,73,${.08+p.z*.35})`;ctx.beginPath();ctx.arc(p.x,p.y,.4+p.z*1.3,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}draw();

fetch('./public/sites.json').then(r=>{if(!r.ok)throw new Error('Content index unavailable');return r.json()}).then(data=>{sites=data;setupTech();applyLanguage();document.querySelector('#heroCount').textContent=sites.length}).catch(err=>{console.error(err);empty.classList.add('show')});
