const sites=window.SITES;const grid=document.querySelector('#grid');const search=document.querySelector('#search');const techFilter=document.querySelector('#techFilter');const soundOnly=document.querySelector('#soundOnly');const resultCount=document.querySelector('#resultCount');const empty=document.querySelector('#empty');let category='All';
const categories=['All','3D World','Particles','Mouse','Scroll','Game','Generative','Sound','Experimental'];const categoryFilters=document.querySelector('#categoryFilters');categories.forEach(c=>{const b=document.createElement('button');b.textContent=c==='All'?'全部':c;b.dataset.category=c;b.className=c==='All'?'active':'';b.onclick=()=>{category=c;categoryFilters.querySelector('.active').classList.remove('active');b.classList.add('active');render()};categoryFilters.appendChild(b)});
[...new Set(sites.flatMap(x=>x.t))].sort().forEach(t=>techFilter.add(new Option(t,t)));
const tones=['#172721','#202034','#32151c','#13252c','#282116','#231630','#0f2d2a','#2e2415'];
function card(s,i){const accent=['#c8ff36','#ff775a','#72d9ff','#e4a8ff','#ffcf5c'][i%5];return `<a class="card" href="${s.u}" target="_blank" rel="noreferrer" style="--tone:${tones[i%tones.length]};--accent:${accent};--rot:${i*23}deg;--mx:${i%2?'-8%':'8%'};--my:${i%3?'-5%':'6%'}"><div class="cover"><div class="mesh"></div><span class="cover-num">${String(i+1).padStart(3,'0')} / ${s.c.toUpperCase()}</span><span class="cover-arrow">↗</span></div><div class="card-body"><div class="card-title"><h3>${s.n}</h3><span>${new URL(s.u).hostname.replace('www.','')}</span></div><p>${s.d}</p><div class="tags">${s.t.map(x=>`<span>${x}</span>`).join('')}${s.i.map(x=>`<span class="interaction">${x}</span>`).join('')}</div></div></a>`}
function filtered(){const q=search.value.trim().toLowerCase();return sites.filter(s=>(category==='All'||s.c===category)&&(techFilter.value==='all'||s.t.includes(techFilter.value))&&(!soundOnly.checked||s.s)&&(!q||[s.n,s.d,s.c,...s.t,...s.i].join(' ').toLowerCase().includes(q)))}
function render(){const list=filtered();grid.innerHTML=list.map((s,i)=>card(s,sites.indexOf(s))).join('');resultCount.textContent=`${String(list.length).padStart(2,'0')} EXPERIENCES`;empty.classList.toggle('show',!list.length)}
[search,techFilter,soundOnly].forEach(el=>el.addEventListener(el===search?'input':'change',render));document.querySelector('#clearBtn').onclick=()=>{search.value='';techFilter.value='all';soundOnly.checked=false;category='All';categoryFilters.querySelector('.active').classList.remove('active');categoryFilters.firstChild.classList.add('active');render()};document.querySelector('#randomBtn').onclick=()=>{const list=filtered();if(list.length)window.open(list[Math.floor(Math.random()*list.length)].u,'_blank','noopener')};render();

const canvas=document.querySelector('#ambient'),ctx=canvas.getContext('2d');let particles=[];let mouse={x:.7,y:.3};function resize(){canvas.width=innerWidth*Math.min(devicePixelRatio,2);canvas.height=innerHeight*Math.min(devicePixelRatio,2);particles=Array.from({length:Math.min(180,Math.floor(innerWidth/7))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,z:Math.random(),v:.1+Math.random()*.4}))}addEventListener('resize',resize);addEventListener('pointermove',e=>mouse={x:e.clientX/innerWidth,y:e.clientY/innerHeight});resize();function draw(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#080909';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(w*mouse.x,h*mouse.y,0,w*mouse.x,h*mouse.y,w*.65);g.addColorStop(0,'rgba(113,142,28,.12)');g.addColorStop(.4,'rgba(24,34,20,.06)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(const p of particles){p.y-=p.v;p.x+=Math.sin(p.y*.003)*.08;if(p.y<0){p.y=h;p.x=Math.random()*w}ctx.fillStyle=`rgba(205,255,73,${.08+p.z*.35})`;ctx.beginPath();ctx.arc(p.x,p.y,.4+p.z*1.3,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}draw();
