window.SITES = [
  {n:'GPT-6 Astra',u:'https://openai.com/index/gpt-6-astra/',c:'Particles',t:['WebGL','Particles'],i:['Mouse','Scroll'],s:0,d:'可拖拽旋转的粒子星系与长篇滚动发布叙事。'},
  {n:'Bruno Simon',u:'https://bruno-simon.com/',c:'Game',t:['Three.js','Physics'],i:['Keyboard'],s:1,d:'驾驶一辆玩具车，在完整的三维世界中探索作品。'},
  {n:'Lusion',u:'https://lusion.co/',c:'3D World',t:['WebGL','GLSL'],i:['Mouse','Scroll'],s:1,d:'电影质感的实时三维、流体模拟与空间转场。'},
  {n:'Active Theory',u:'https://activetheory.net/',c:'3D World',t:['WebGL','GLSL'],i:['Mouse','Sound'],s:1,d:'接近游戏引擎质感的沉浸空间和声音体验。'},
  {n:'Resn',u:'https://resn.co.nz/',c:'Experimental',t:['WebGL','Canvas'],i:['Mouse','Sound'],s:1,d:'怪诞、不可预测，页面会对鼠标做出夸张反馈。'},
  {n:'Immersive Garden',u:'https://immersive-g.com/',c:'3D World',t:['Three.js','GLSL'],i:['Mouse','Scroll'],s:1,d:'梦境般的数字花园、自然材质和空间镜头。'},
  {n:'Dogstudio',u:'https://dogstudio.co/',c:'3D World',t:['WebGL','GSAP'],i:['Scroll'],s:1,d:'角色、场景和镜头共同组成电影式网页体验。'},
  {n:'Basement Studio',u:'https://basement.studio/',c:'Scroll',t:['R3F','Physics'],i:['Scroll','Mouse'],s:0,d:'平面卡片像真实物体一样具有空间和物理惯性。'},
  {n:'Unseen Studio',u:'https://unseen.co/',c:'Experimental',t:['WebGL','GLSL'],i:['Mouse','Scroll'],s:0,d:'柔软形变、光泽材质与克制的未来主义设计。'},
  {n:'Garden Eight',u:'https://garden-eight.com/',c:'Scroll',t:['WebGL','GSAP'],i:['Mouse','Scroll'],s:0,d:'精致的日系排版、空间层次和细腻的交互反馈。'},
  {n:'Locomotive',u:'https://locomotive.ca/',c:'Scroll',t:['GSAP','Canvas'],i:['Scroll'],s:0,d:'惯性滚动、巨型字体和镜头式页面衔接。'},
  {n:'Make Me Pulse',u:'https://makemepulse.com/',c:'Experimental',t:['WebGL','GLSL'],i:['Mouse','Sound'],s:1,d:'具有呼吸感的有机图形、声音和实验性互动。'},
  {n:'Cuberto',u:'https://cuberto.com/',c:'Mouse',t:['GSAP','Canvas'],i:['Mouse','Scroll'],s:0,d:'鼠标跟随、磁吸按钮和丝滑的页面过渡。'},
  {n:'Studio Freight',u:'https://studiofreight.com/',c:'Scroll',t:['GSAP','Canvas'],i:['Mouse','Scroll'],s:0,d:'强排版与带有重量感的惯性和物理动画。'},
  {n:'OBYS',u:'https://obys.agency/',c:'Scroll',t:['GSAP','WebGL'],i:['Mouse','Scroll'],s:0,d:'先锋字体、编辑设计和电影般的滚动转场。'},
  {n:'Akaru',u:'https://akaru.fr/',c:'Experimental',t:['WebGL','GSAP'],i:['Mouse','Scroll'],s:0,d:'法式艺术指导与富有节奏的实验动画。'},
  {n:'Aristide Benoist',u:'https://aristidebenoist.com/',c:'Scroll',t:['WebGL','GSAP'],i:['Mouse','Scroll'],s:0,d:'极简构图和精确到帧的滚动动画编排。'},
  {n:'Hello Monday',u:'https://hellomonday.com/',c:'Game',t:['Canvas','WebGL'],i:['Mouse','Sound'],s:1,d:'把插画、故事和游戏机制融合进品牌网页。'},
  {n:'Monopo London',u:'https://monopo.london/',c:'Mouse',t:['GSAP','Canvas'],i:['Mouse','Scroll'],s:0,d:'大胆色彩、杂志排版和灵敏的指针反馈。'},
  {n:'Rally Interactive',u:'https://rallyinteractive.com/',c:'3D World',t:['WebGL','Canvas'],i:['Mouse','Scroll'],s:1,d:'高完成度的互动品牌叙事和数字空间。'},
  {n:'Apple Vision Pro',u:'https://www.apple.com/apple-vision-pro/',c:'Scroll',t:['WebGL','Canvas'],i:['Scroll'],s:1,d:'产品随滚动拆解、旋转并进入使用情境。'},
  {n:'Apple AirPods Pro',u:'https://www.apple.com/airpods-pro/',c:'Scroll',t:['Canvas','GSAP'],i:['Scroll','Sound'],s:1,d:'空间音频概念和电影式产品展示。'},
  {n:'Stripe',u:'https://stripe.com/',c:'Generative',t:['WebGL','GLSL'],i:['Mouse'],s:0,d:'像光穿过玻璃一样流动的实时渐变表面。'},
  {n:'Huly',u:'https://huly.io/',c:'3D World',t:['Spline','WebGL'],i:['Mouse','Scroll'],s:0,d:'悬浮的三维产品界面随光标产生细微视差。'},
  {n:'Resend',u:'https://resend.com/',c:'3D World',t:['Three.js','GLSL'],i:['Mouse'],s:0,d:'极简几何体搭配虹彩材质和柔和旋转。'},
  {n:'Spline',u:'https://spline.design/',c:'3D World',t:['Spline','WebGL'],i:['Mouse'],s:0,d:'在线创建、操控并发布具有交互的三维场景。'},
  {n:'Porsche',u:'https://www.porsche.com/',c:'3D World',t:['WebGL','Canvas'],i:['Mouse','Scroll'],s:1,d:'汽车材质、空间镜头与高端产品叙事。'},
  {n:'Polestar',u:'https://www.polestar.com/',c:'3D World',t:['WebGL','GSAP'],i:['Mouse','Scroll'],s:0,d:'克制的汽车三维展示和结构化滚动体验。'},
  {n:'Nothing',u:'https://nothing.tech/',c:'Scroll',t:['WebGL','GSAP'],i:['Mouse','Scroll'],s:0,d:'透明工业材质、像素字体与强烈品牌动效。'},
  {n:'Ray-Ban Meta',u:'https://www.ray-ban.com/usa/discover-ray-ban-meta-ai-glasses/clp',c:'Scroll',t:['WebGL','Canvas'],i:['Scroll','Video'],s:1,d:'眼镜产品旋转并随着滚动切换功能场景。'},
  {n:'Particle Love',u:'https://particle-love.com/',c:'Particles',t:['WebGL','Particles'],i:['Mouse'],s:0,d:'粒子在光标附近聚合、逃逸和留下运动轨迹。'},
  {n:'WebGL Fluid',u:'https://paveldogreat.github.io/WebGL-Fluid-Simulation/',c:'Generative',t:['WebGL','GLSL'],i:['Mouse'],s:0,d:'用鼠标搅动色彩丰富的实时液体和旋涡。'},
  {n:'Blobmixer',u:'https://blobmixer.14islands.com/',c:'Generative',t:['Three.js','GLSL'],i:['Mouse'],s:0,d:'捏合、拉扯和混合具有弹性的三维软体。'},
  {n:'Silk',u:'http://weavesilk.com/',c:'Generative',t:['Canvas'],i:['Mouse'],s:0,d:'用光标绘制具有镜像对称的发光丝线。'},
  {n:'Patatap',u:'https://patatap.com/',c:'Sound',t:['Canvas','Web Audio'],i:['Keyboard','Sound'],s:1,d:'每次键盘输入都会触发独特的动态图形和声音。'},
  {n:'Blob Opera',u:'https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw',c:'Sound',t:['WebGL','Web Audio'],i:['Mouse','Sound'],s:1,d:'拖动可爱的软体角色来控制音高并组成合唱。'},
  {n:'WebGL Aquarium',u:'https://webglsamples.org/aquarium/aquarium.html',c:'3D World',t:['WebGL'],i:['Mouse'],s:0,d:'经典的大规模鱼群动画与实时水下空间。'},
  {n:'Three.js Examples',u:'https://threejs.org/examples/',c:'Experimental',t:['Three.js','WebGL'],i:['Mouse','Keyboard'],s:0,d:'涵盖粒子、Shader、物理和后处理的实验库。'},
  {n:'R3F Examples',u:'https://docs.pmnd.rs/react-three-fiber/getting-started/examples',c:'Experimental',t:['R3F','Three.js'],i:['Mouse'],s:0,d:'React 技术体系下的实时三维互动案例集合。'},
  {n:'Chrome Experiments',u:'https://experiments.withgoogle.com/collection/chrome',c:'Experimental',t:['Canvas','WebGL'],i:['Mouse','Sound'],s:1,d:'浏览器生成艺术、声音与交互技术的经典档案。'},
  {n:'Paper Planes',u:'https://paperplanes.world/',c:'Game',t:['WebGL','Canvas'],i:['Mouse','Gyroscope'],s:1,d:'折一架纸飞机，将它投向由全球玩家组成的天空。'},
  {n:'Species in Pieces',u:'http://www.species-in-pieces.com/',c:'Scroll',t:['SVG','CSS'],i:['Mouse','Scroll'],s:1,d:'用不断变形的多边形讲述濒危动物的故事。'},
  {n:'The Boat',u:'https://www.sbs.com.au/theboat/',c:'Scroll',t:['Canvas','GSAP'],i:['Scroll','Sound'],s:1,d:'插画、视差和声音构成的沉浸式图像小说。'},
  {n:'Radio Garden',u:'https://radio.garden/',c:'Sound',t:['WebGL','Web Audio'],i:['Mouse','Sound'],s:1,d:'旋转三维地球，实时收听世界各地的广播。'},
  {n:'NASA Eyes',u:'https://eyes.nasa.gov/',c:'3D World',t:['WebGL','Data'],i:['Mouse'],s:0,d:'在实时三维空间中探索太阳系、地球和航天器。'},
  {n:'Solar System Scope',u:'https://www.solarsystemscope.com/',c:'3D World',t:['WebGL','Three.js'],i:['Mouse'],s:1,d:'自由缩放、旋转并观察完整太阳系。'},
  {n:'Earth Nullschool',u:'https://earth.nullschool.net/',c:'Particles',t:['WebGL','Data'],i:['Mouse'],s:0,d:'在旋转地球上观察实时全球风场和气象数据。'},
  {n:'Deep Sea',u:'https://neal.fun/deep-sea/',c:'Scroll',t:['Canvas','CSS'],i:['Scroll'],s:0,d:'持续向下滚动，感受海洋深度和生物尺度。'},
  {n:'Space Elevator',u:'https://neal.fun/space-elevator/',c:'Scroll',t:['Canvas','CSS'],i:['Scroll'],s:0,d:'沿太空电梯不断上升，穿越大气层直到宇宙。'},
  {n:'Pointer Pointer',u:'https://pointerpointer.com/',c:'Mouse',t:['JavaScript','Images'],i:['Mouse'],s:0,d:'无论光标停在哪里，都找到一张指向它的照片。'}
];
